
CREATE TYPE status_enum AS ENUM (
    'EM_ANALISE',
	'ANALISE_REALIZADA',
	'ANALISE_APROVADA',
	'INICIADO',
	'PLANEJADO',
	'EM_ANDAMENTO',
	'ENCERRADO',
	'CANCELADO');

CREATE TYPE risco_enum AS ENUM (
	'BAIXO',
	'MEDIO',
	'ALTO');

CREATE TABLE pessoa (
  ID BIGINT GENERATED BY DEFAULT AS IDENTITY(NO CACHE) PRIMARY KEY, 
  nome VARCHAR(100) NOT NULL, 
  data_nascimento date, 
  cpf VARCHAR(14), 
  funcionario boolean
);


CREATE TABLE projeto (
  ID BIGINT GENERATED BY DEFAULT AS IDENTITY(NO CACHE) PRIMARY KEY, 
  nome VARCHAR(200) NOT NULL, 
  data_inicio DATE, 
  data_previsao_fim DATE, 
  data_fim DATE, 
  descricao VARCHAR(5000), 
  status VARCHAR(45), 
  orcamento FLOAT, 
  risco VARCHAR(45), 
  gerente_id BIGINT NOT NULL, 
  CONSTRAINT pk_projeto PRIMARY KEY (id), 
  CONSTRAINT fk_gerente FOREIGN KEY (gerente_id) REFERENCES pessoa (id) 
);

CREATE TABLE membro (
  ID BIGINT GENERATED BY DEFAULT AS IDENTITY(NO CACHE) PRIMARY KEY,
  projeto_id BIGINT NOT NULL, 
  pessoa_id BIGINT NOT NULL, 
  cargo VARCHAR(100) NOT NULL, 
  CONSTRAINT fk_membro_pessoa FOREIGN KEY (pessoa_id) REFERENCES pessoa (id), 
  CONSTRAINT fk_membro_projeto FOREIGN KEY (projeto_id) REFERENCES projeto (id)
);

